"""reset_initial

Revision ID: 83b03c6bb879
Revises: a660585d9c09
Create Date: 2026-01-26 13:55:15.806910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83b03c6bb879'
down_revision: Union[str, None] = 'a660585d9c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cong_chuc', schema=None) as batch_op:
        batch_op.alter_column('ma_cc',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã công chức',
               existing_comment='Mã công chức (unique, làm username)',
               existing_nullable=False)
        batch_op.alter_column('ho_ten',
               existing_type=sa.VARCHAR(length=100),
               comment='Họ và tên',
               existing_comment='Họ và tên đầy đủ',
               existing_nullable=False)
        batch_op.alter_column('gioi_tinh',
               existing_type=postgresql.ENUM('NAM', 'NU', name='gioi_tinh_enum'),
               comment='Giới tính',
               existing_comment='Giới tính: NAM, NU',
               existing_nullable=True)
        batch_op.alter_column('so_dien_thoai',
               existing_type=sa.VARCHAR(length=20),
               comment='Số điện thoại',
               existing_comment='Số điện thoại liên hệ',
               existing_nullable=True)
        batch_op.alter_column('vai_tro_id',
               existing_type=sa.UUID(),
               comment='ID vai trò',
               existing_comment='ID vai trò trong hệ thống',
               existing_nullable=False)
        batch_op.alter_column('chuc_vu',
               existing_type=sa.VARCHAR(length=100),
               comment='Chức vụ hiển thị',
               existing_comment='Chức vụ hiển thị (VD: Chánh Văn phòng)',
               existing_nullable=True)
        batch_op.alter_column('ngay_vao_nganh',
               existing_type=sa.DATE(),
               comment='Ngày vào ngành',
               existing_comment='Ngày vào ngành Hải quan',
               existing_nullable=True)
        batch_op.alter_column('ngay_vao_chi_cuc',
               existing_type=sa.DATE(),
               comment='Ngày về Chi cục',
               existing_comment='Ngày về Chi cục KV VIII',
               existing_nullable=True)
        batch_op.alter_column('is_lanh_dao',
               existing_type=sa.BOOLEAN(),
               comment='Có phải lãnh đạo không',
               existing_comment='Có phải lãnh đạo không (denormalized từ vai_tro)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               comment='Tên đăng nhập',
               existing_comment='Tên đăng nhập (mặc định = ma_cc)',
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Mật khẩu đã hash',
               existing_comment='Mật khẩu đã hash (bcrypt)',
               existing_nullable=True)

    with op.batch_alter_table('dang_ky_nghi', schema=None) as batch_op:
        batch_op.alter_column('loai_nghi',
               existing_type=postgresql.ENUM('NGHI_TUAN', 'PHEP_NAM', 'NGHI_LE', 'NGHI_OM', 'THAI_SAN', 'VIEC_RIENG', 'KHONG_LUONG', 'NGHI_BU', 'KHAC', name='loai_nghi_enum'),
               comment='Loại nghỉ phép',
               existing_comment='Loại nghỉ phép (NGHI_TUAN, PHEP_NAM, NGHI_LE, ...)',
               existing_nullable=False)
        batch_op.alter_column('so_ngay',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               comment='Số ngày nghỉ thực tế (cho phép 0.5)',
               existing_comment='Số ngày nghỉ thực tế (cho phép 0.5 để nghỉ buổi)',
               existing_nullable=False)
        batch_op.alter_column('tai_lieu_dinh_kem',
               existing_type=sa.VARCHAR(length=500),
               comment='Đường dẫn file đính kèm',
               existing_comment='Đường dẫn file đính kèm (giấy khám bệnh, giấy mời...)',
               existing_nullable=True)
        batch_op.alter_column('nguoi_phe_duyet_id',
               existing_type=sa.UUID(),
               comment='ID người phê duyệt',
               existing_comment='ID người phê duyệt (CC chọn Phó ĐV)',
               existing_nullable=True)
        batch_op.alter_column('ly_do_tu_choi',
               existing_type=sa.TEXT(),
               comment='Lý do từ chối',
               existing_comment='Lý do từ chối (nếu bị từ chối)',
               existing_nullable=True)
        batch_op.alter_column('da_tinh_kpi',
               existing_type=sa.BOOLEAN(),
               comment='Đánh dấu đã được tính vào KPI chưa',
               existing_comment='Đánh dấu đã được tính vào KPI chưa (tránh tính trùng)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('don_vi', schema=None) as batch_op:
        batch_op.alter_column('ten_viet_tat',
               existing_type=sa.VARCHAR(length=50),
               comment='Tên viết tắt',
               existing_comment='Tên viết tắt (VD: VP, TCCB, HQCK-HG)',
               existing_nullable=True)
        batch_op.alter_column('loai_don_vi',
               existing_type=postgresql.ENUM('LANH_DAO_CHI_CUC', 'PHONG', 'DOI', 'HAI_QUAN_CUA_KHAU', name='loai_don_vi_enum'),
               comment='Loại đơn vị',
               existing_comment='Loại đơn vị: PHONG, DOI, HAI_QUAN_CUA_KHAU',
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.UUID(),
               comment='ID đơn vị cha',
               existing_comment='ID đơn vị cha (nếu có phân cấp)',
               existing_nullable=True)
        batch_op.alter_column('thu_tu_hien_thi',
               existing_type=sa.INTEGER(),
               comment='Thứ tự hiển thị',
               existing_comment='Thứ tự hiển thị trong danh sách',
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('vai_tro', schema=None) as batch_op:
        batch_op.alter_column('ma_vai_tro',
               existing_type=sa.VARCHAR(length=50),
               comment='Mã vai trò',
               existing_comment='Mã vai trò (VD: CCT, PCCT, TDV)',
               existing_nullable=False)
        batch_op.alter_column('ten_vai_tro',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên hiển thị',
               existing_comment='Tên hiển thị (VD: Chi cục trưởng)',
               existing_nullable=False)
        batch_op.alter_column('cap_bac',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'CHI_CUC_TRUONG', 'PHO_CHI_CUC_TRUONG', 'TRUONG_DON_VI', 'PHO_DON_VI', 'CONG_CHUC', 'TCCB', name='cap_bac_vai_tro_enum'),
               comment='Cấp bậc trong hệ thống',
               existing_comment='Cấp bậc trong hệ thống phân quyền',
               existing_nullable=False)
        batch_op.alter_column('mo_ta',
               existing_type=sa.TEXT(),
               comment='Mô tả chi tiết',
               existing_comment='Mô tả chi tiết vai trò',
               existing_nullable=True)
        batch_op.alter_column('is_lanh_dao',
               existing_type=sa.BOOLEAN(),
               comment='Có phải lãnh đạo không',
               existing_comment='Có phải lãnh đạo không (CCT, PCCT, TDV, PDV)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_system_admin',
               existing_type=sa.BOOLEAN(),
               comment='Là Super Admin',
               existing_comment='Là Super Admin (KHÔNG tham gia nghiệp vụ)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('quyen_han',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Danh sách quyền chi tiết',
               existing_comment='Danh sách quyền chi tiết (JSON)',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vai_tro', schema=None) as batch_op:
        batch_op.alter_column('quyen_han',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Danh sách quyền chi tiết (JSON)',
               existing_comment='Danh sách quyền chi tiết',
               existing_nullable=True)
        batch_op.alter_column('is_system_admin',
               existing_type=sa.BOOLEAN(),
               comment='Là Super Admin (KHÔNG tham gia nghiệp vụ)',
               existing_comment='Là Super Admin',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_lanh_dao',
               existing_type=sa.BOOLEAN(),
               comment='Có phải lãnh đạo không (CCT, PCCT, TDV, PDV)',
               existing_comment='Có phải lãnh đạo không',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('mo_ta',
               existing_type=sa.TEXT(),
               comment='Mô tả chi tiết vai trò',
               existing_comment='Mô tả chi tiết',
               existing_nullable=True)
        batch_op.alter_column('cap_bac',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'CHI_CUC_TRUONG', 'PHO_CHI_CUC_TRUONG', 'TRUONG_DON_VI', 'PHO_DON_VI', 'CONG_CHUC', 'TCCB', name='cap_bac_vai_tro_enum'),
               comment='Cấp bậc trong hệ thống phân quyền',
               existing_comment='Cấp bậc trong hệ thống',
               existing_nullable=False)
        batch_op.alter_column('ten_vai_tro',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên hiển thị (VD: Chi cục trưởng)',
               existing_comment='Tên hiển thị',
               existing_nullable=False)
        batch_op.alter_column('ma_vai_tro',
               existing_type=sa.VARCHAR(length=50),
               comment='Mã vai trò (VD: CCT, PCCT, TDV)',
               existing_comment='Mã vai trò',
               existing_nullable=False)

    with op.batch_alter_table('don_vi', schema=None) as batch_op:
        batch_op.alter_column('thu_tu_hien_thi',
               existing_type=sa.INTEGER(),
               comment='Thứ tự hiển thị trong danh sách',
               existing_comment='Thứ tự hiển thị',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('parent_id',
               existing_type=sa.UUID(),
               comment='ID đơn vị cha (nếu có phân cấp)',
               existing_comment='ID đơn vị cha',
               existing_nullable=True)
        batch_op.alter_column('loai_don_vi',
               existing_type=postgresql.ENUM('LANH_DAO_CHI_CUC', 'PHONG', 'DOI', 'HAI_QUAN_CUA_KHAU', name='loai_don_vi_enum'),
               comment='Loại đơn vị: PHONG, DOI, HAI_QUAN_CUA_KHAU',
               existing_comment='Loại đơn vị',
               existing_nullable=False)
        batch_op.alter_column('ten_viet_tat',
               existing_type=sa.VARCHAR(length=50),
               comment='Tên viết tắt (VD: VP, TCCB, HQCK-HG)',
               existing_comment='Tên viết tắt',
               existing_nullable=True)

    with op.batch_alter_table('dang_ky_nghi', schema=None) as batch_op:
        batch_op.alter_column('da_tinh_kpi',
               existing_type=sa.BOOLEAN(),
               comment='Đánh dấu đã được tính vào KPI chưa (tránh tính trùng)',
               existing_comment='Đánh dấu đã được tính vào KPI chưa',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ly_do_tu_choi',
               existing_type=sa.TEXT(),
               comment='Lý do từ chối (nếu bị từ chối)',
               existing_comment='Lý do từ chối',
               existing_nullable=True)
        batch_op.alter_column('nguoi_phe_duyet_id',
               existing_type=sa.UUID(),
               comment='ID người phê duyệt (CC chọn Phó ĐV)',
               existing_comment='ID người phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('tai_lieu_dinh_kem',
               existing_type=sa.VARCHAR(length=500),
               comment='Đường dẫn file đính kèm (giấy khám bệnh, giấy mời...)',
               existing_comment='Đường dẫn file đính kèm',
               existing_nullable=True)
        batch_op.alter_column('so_ngay',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               comment='Số ngày nghỉ thực tế (cho phép 0.5 để nghỉ buổi)',
               existing_comment='Số ngày nghỉ thực tế (cho phép 0.5)',
               existing_nullable=False)
        batch_op.alter_column('loai_nghi',
               existing_type=postgresql.ENUM('NGHI_TUAN', 'PHEP_NAM', 'NGHI_LE', 'NGHI_OM', 'THAI_SAN', 'VIEC_RIENG', 'KHONG_LUONG', 'NGHI_BU', 'KHAC', name='loai_nghi_enum'),
               comment='Loại nghỉ phép (NGHI_TUAN, PHEP_NAM, NGHI_LE, ...)',
               existing_comment='Loại nghỉ phép',
               existing_nullable=False)

    with op.batch_alter_table('cong_chuc', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Mật khẩu đã hash (bcrypt)',
               existing_comment='Mật khẩu đã hash',
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               comment='Tên đăng nhập (mặc định = ma_cc)',
               existing_comment='Tên đăng nhập',
               existing_nullable=True)
        batch_op.alter_column('is_lanh_dao',
               existing_type=sa.BOOLEAN(),
               comment='Có phải lãnh đạo không (denormalized từ vai_tro)',
               existing_comment='Có phải lãnh đạo không',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ngay_vao_chi_cuc',
               existing_type=sa.DATE(),
               comment='Ngày về Chi cục KV VIII',
               existing_comment='Ngày về Chi cục',
               existing_nullable=True)
        batch_op.alter_column('ngay_vao_nganh',
               existing_type=sa.DATE(),
               comment='Ngày vào ngành Hải quan',
               existing_comment='Ngày vào ngành',
               existing_nullable=True)
        batch_op.alter_column('chuc_vu',
               existing_type=sa.VARCHAR(length=100),
               comment='Chức vụ hiển thị (VD: Chánh Văn phòng)',
               existing_comment='Chức vụ hiển thị',
               existing_nullable=True)
        batch_op.alter_column('vai_tro_id',
               existing_type=sa.UUID(),
               comment='ID vai trò trong hệ thống',
               existing_comment='ID vai trò',
               existing_nullable=False)
        batch_op.alter_column('so_dien_thoai',
               existing_type=sa.VARCHAR(length=20),
               comment='Số điện thoại liên hệ',
               existing_comment='Số điện thoại',
               existing_nullable=True)
        batch_op.alter_column('gioi_tinh',
               existing_type=postgresql.ENUM('NAM', 'NU', name='gioi_tinh_enum'),
               comment='Giới tính: NAM, NU',
               existing_comment='Giới tính',
               existing_nullable=True)
        batch_op.alter_column('ho_ten',
               existing_type=sa.VARCHAR(length=100),
               comment='Họ và tên đầy đủ',
               existing_comment='Họ và tên',
               existing_nullable=False)
        batch_op.alter_column('ma_cc',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã công chức (unique, làm username)',
               existing_comment='Mã công chức',
               existing_nullable=False)

    # ### end Alembic commands ###