"""add_leave_management_table

Revision ID: a660585d9c09
Revises: 003_add_self_evaluation
Create Date: 2026-01-25 22:45:41.200815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a660585d9c09'
down_revision: Union[str, None] = '003_add_self_evaluation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dang_ky_nghi',
    sa.Column('cong_chuc_id', sa.UUID(), nullable=False, comment='ID công chức đăng ký nghỉ'),
    sa.Column('loai_nghi', sa.Enum('NGHI_TUAN', 'PHEP_NAM', 'NGHI_LE', 'NGHI_OM', 'THAI_SAN', 'VIEC_RIENG', 'KHONG_LUONG', 'NGHI_BU', 'KHAC', name='loai_nghi_enum'), nullable=False, comment='Loại nghỉ phép (NGHI_TUAN, PHEP_NAM, NGHI_LE, ...)'),
    sa.Column('tu_ngay', sa.Date(), nullable=False, comment='Ngày bắt đầu nghỉ'),
    sa.Column('den_ngay', sa.Date(), nullable=False, comment='Ngày kết thúc nghỉ'),
    sa.Column('so_ngay', sa.Numeric(precision=4, scale=1), nullable=False, comment='Số ngày nghỉ thực tế (cho phép 0.5 để nghỉ buổi)'),
    sa.Column('ly_do', sa.Text(), nullable=True, comment='Lý do xin nghỉ'),
    sa.Column('tai_lieu_dinh_kem', sa.String(length=500), nullable=True, comment='Đường dẫn file đính kèm (giấy khám bệnh, giấy mời...)'),
    sa.Column('nguoi_phe_duyet_id', sa.UUID(), nullable=True, comment='ID người phê duyệt (CC chọn Phó ĐV)'),
    sa.Column('trang_thai', sa.Enum('CHO_PHE_DUYET', 'DA_PHE_DUYET', 'TU_CHOI', 'HUY', name='trang_thai_nghi_enum'), server_default='CHO_PHE_DUYET', nullable=False, comment='Trạng thái đơn nghỉ'),
    sa.Column('ly_do_tu_choi', sa.Text(), nullable=True, comment='Lý do từ chối (nếu bị từ chối)'),
    sa.Column('ngay_phe_duyet', sa.DateTime(timezone=True), nullable=True, comment='Thời điểm phê duyệt/từ chối'),
    sa.Column('ghi_chu_phe_duyet', sa.Text(), nullable=True, comment='Ghi chú của người phê duyệt'),
    sa.Column('thang_ap_dung', sa.Integer(), nullable=True, comment='Tháng áp dụng cho tính KPI (1-12)'),
    sa.Column('nam_ap_dung', sa.Integer(), nullable=True, comment='Năm áp dụng cho tính KPI'),
    sa.Column('da_tinh_kpi', sa.Boolean(), server_default='false', nullable=False, comment='Đánh dấu đã được tính vào KPI chưa (tránh tính trùng)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary Key (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời gian tạo record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời gian cập nhật cuối'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Đánh dấu đã xóa (soft delete)'),
    sa.CheckConstraint('den_ngay >= tu_ngay', name='ck_dang_ky_nghi_ngay'),
    sa.CheckConstraint('nam_ap_dung IS NULL OR nam_ap_dung >= 2025', name='ck_dang_ky_nghi_nam'),
    sa.CheckConstraint('so_ngay > 0 AND so_ngay <= 365', name='ck_dang_ky_nghi_so_ngay'),
    sa.CheckConstraint('thang_ap_dung IS NULL OR (thang_ap_dung BETWEEN 1 AND 12)', name='ck_dang_ky_nghi_thang'),
    sa.ForeignKeyConstraint(['cong_chuc_id'], ['cong_chuc.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nguoi_phe_duyet_id'], ['cong_chuc.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dang_ky_nghi', schema=None) as batch_op:
        batch_op.create_index('idx_dang_ky_nghi_cc', ['cong_chuc_id'], unique=False)
        batch_op.create_index('idx_dang_ky_nghi_kpi', ['cong_chuc_id', 'thang_ap_dung', 'nam_ap_dung', 'trang_thai'], unique=False, postgresql_where="trang_thai = 'DA_PHE_DUYET' AND is_deleted = FALSE")
        batch_op.create_index('idx_dang_ky_nghi_loai', ['loai_nghi'], unique=False)
        batch_op.create_index('idx_dang_ky_nghi_ngay', ['tu_ngay', 'den_ngay'], unique=False)
        batch_op.create_index('idx_dang_ky_nghi_phe_duyet', ['nguoi_phe_duyet_id'], unique=False)
        batch_op.create_index('idx_dang_ky_nghi_thang_nam', ['thang_ap_dung', 'nam_ap_dung'], unique=False)
        batch_op.create_index('idx_dang_ky_nghi_trang_thai', ['trang_thai'], unique=False)
        batch_op.create_index(batch_op.f('ix_dang_ky_nghi_cong_chuc_id'), ['cong_chuc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dang_ky_nghi_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_dang_ky_nghi_loai_nghi'), ['loai_nghi'], unique=False)
        batch_op.create_index(batch_op.f('ix_dang_ky_nghi_nguoi_phe_duyet_id'), ['nguoi_phe_duyet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dang_ky_nghi_trang_thai'), ['trang_thai'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('table_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên bảng bị thay đổi',
               existing_nullable=False)
        batch_op.alter_column('record_id',
               existing_type=sa.UUID(),
               comment='ID của record bị thay đổi',
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=postgresql.ENUM('INSERT', 'UPDATE', 'DELETE', name='audit_action_enum'),
               comment='Loại hành động: INSERT/UPDATE/DELETE',
               existing_nullable=False)
        batch_op.alter_column('old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Giá trị cũ (cho UPDATE/DELETE)',
               existing_nullable=True)
        batch_op.alter_column('new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Giá trị mới (cho INSERT/UPDATE)',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               comment='ID người thực hiện (từ app.current_user_id)',
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               comment='IP address của request',
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               comment='User agent của request',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời điểm thay đổi',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.drop_index('idx_audit_action')
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='Audit log - ghi lại mọi thay đổi dữ liệu'
    )

    with op.batch_alter_table('cap_do_phuc_tap', schema=None) as batch_op:
        batch_op.alter_column('ma_cap_do',
               existing_type=sa.VARCHAR(length=10),
               comment='Mã cấp độ: C1, C2, C3, C4, C5',
               existing_nullable=False)
        batch_op.alter_column('ten_cap_do',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên cấp độ (VD: Dễ - Đơn giản)',
               existing_nullable=False)
        batch_op.alter_column('mo_ta',
               existing_type=sa.TEXT(),
               comment='Mô tả tiêu chí phân loại',
               existing_nullable=True)
        batch_op.alter_column('he_so_sp1',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Hệ số nhân khi áp dụng cho SP1',
               existing_nullable=False)
        batch_op.alter_column('he_so_sp2',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Hệ số nhân khi áp dụng cho SP2/SP3/SP4',
               existing_nullable=False)
        batch_op.alter_column('is_theo_thuc_te',
               existing_type=sa.BOOLEAN(),
               comment='C5 = TRUE (hệ số do lãnh đạo nhập)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('thu_tu',
               existing_type=sa.INTEGER(),
               comment='Thứ tự sắp xếp (1-5)',
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment='Còn sử dụng',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_table_comment(
        existing_comment='Cấp độ phức tạp công việc (C1-C5)'
    )

    with op.batch_alter_table('cong_chuc', schema=None) as batch_op:
        batch_op.alter_column('ma_cc',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã công chức (unique, làm username)',
               existing_nullable=False)
        batch_op.alter_column('ho_ten',
               existing_type=sa.VARCHAR(length=100),
               comment='Họ và tên đầy đủ',
               existing_nullable=False)
        batch_op.alter_column('ngay_sinh',
               existing_type=sa.DATE(),
               comment='Ngày sinh',
               existing_nullable=True)
        batch_op.alter_column('gioi_tinh',
               existing_type=postgresql.ENUM('NAM', 'NU', name='gioi_tinh_enum'),
               comment='Giới tính: NAM, NU',
               existing_nullable=True)
        batch_op.alter_column('so_dien_thoai',
               existing_type=sa.VARCHAR(length=20),
               comment='Số điện thoại liên hệ',
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               comment='Email công vụ',
               existing_nullable=True)
        batch_op.alter_column('don_vi_id',
               existing_type=sa.UUID(),
               comment='ID đơn vị công tác',
               existing_nullable=False)
        batch_op.alter_column('vai_tro_id',
               existing_type=sa.UUID(),
               comment='ID vai trò trong hệ thống',
               existing_nullable=False)
        batch_op.alter_column('chuc_vu',
               existing_type=sa.VARCHAR(length=100),
               comment='Chức vụ hiển thị (VD: Chánh Văn phòng)',
               existing_nullable=True)
        batch_op.alter_column('ngay_vao_nganh',
               existing_type=sa.DATE(),
               comment='Ngày vào ngành Hải quan',
               existing_nullable=True)
        batch_op.alter_column('ngay_vao_chi_cuc',
               existing_type=sa.DATE(),
               comment='Ngày về Chi cục KV VIII',
               existing_nullable=True)
        batch_op.alter_column('is_lanh_dao',
               existing_type=sa.BOOLEAN(),
               comment='Có phải lãnh đạo không (denormalized từ vai_tro)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment='Tài khoản còn hoạt động',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               comment='Tên đăng nhập (mặc định = ma_cc)',
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Mật khẩu đã hash (bcrypt)',
               existing_nullable=True)
        batch_op.alter_column('last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Lần đăng nhập cuối',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Đánh dấu đã xóa (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_constraint('cong_chuc_ma_cc_key', type_='unique')
        batch_op.drop_constraint('cong_chuc_username_key', type_='unique')
        batch_op.drop_index('idx_cong_chuc_username')
        batch_op.create_index(batch_op.f('ix_cong_chuc_don_vi_id'), ['don_vi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cong_chuc_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_cong_chuc_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_cong_chuc_ma_cc'), ['ma_cc'], unique=True)
        batch_op.create_index(batch_op.f('ix_cong_chuc_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_cong_chuc_vai_tro_id'), ['vai_tro_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='Công chức Chi cục Hải quan KV8'
    )

    with op.batch_alter_table('danh_gia_thang', schema=None) as batch_op:
        batch_op.alter_column('cong_chuc_id',
               existing_type=sa.UUID(),
               comment='ID công chức được đánh giá',
               existing_nullable=False)
        batch_op.alter_column('thang',
               existing_type=sa.INTEGER(),
               comment='Tháng đánh giá (1-12)',
               existing_nullable=False)
        batch_op.alter_column('nam',
               existing_type=sa.INTEGER(),
               comment='Năm đánh giá',
               existing_nullable=False)
        batch_op.alter_column('so_sp_goc_duoc_giao',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Số SP gốc được giao (tự động tính)',
               existing_nullable=True)
        batch_op.alter_column('so_ngay_lam_viec',
               existing_type=sa.INTEGER(),
               comment='Số ngày làm việc trong tháng',
               existing_nullable=True)
        batch_op.alter_column('so_ngay_nghi_phep',
               existing_type=sa.INTEGER(),
               comment='Số ngày nghỉ phép',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('diem_tieu_chi_chung',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Tổng điểm tiêu chí chung (0-30)',
               existing_nullable=True)
        batch_op.alter_column('diem_kpi',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Điểm KPI (tỷ lệ 0-1)',
               existing_nullable=True)
        batch_op.alter_column('diem_so_luong',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Điểm số lượng (a)',
               existing_nullable=True)
        batch_op.alter_column('diem_chat_luong',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Điểm chất lượng (b)',
               existing_nullable=True)
        batch_op.alter_column('diem_tien_do',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Điểm tiến độ (c)',
               existing_nullable=True)
        batch_op.alter_column('diem_tong',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Điểm tổng (0-100)',
               existing_nullable=True)
        batch_op.alter_column('muc_xep_loai_tu_dong',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='muc_xep_loai_enum'),
               comment='Mức xếp loại tự động (theo điểm)',
               existing_nullable=True)
        batch_op.alter_column('muc_xep_loai_de_xuat',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='muc_xep_loai_enum'),
               comment='Mức xếp loại Trưởng ĐV đề xuất',
               existing_nullable=True)
        batch_op.alter_column('muc_xep_loai_chinh_thuc',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='muc_xep_loai_enum'),
               comment='Mức xếp loại chính thức (CCT quyết định)',
               existing_nullable=True)
        batch_op.alter_column('ly_do_dieu_chinh',
               existing_type=sa.TEXT(),
               comment='Lý do nếu khác với xếp loại tự động',
               existing_nullable=True)
        batch_op.alter_column('nguoi_de_xuat_id',
               existing_type=sa.UUID(),
               comment='ID Trưởng ĐV đề xuất',
               existing_nullable=True)
        batch_op.alter_column('nguoi_phe_duyet_id',
               existing_type=sa.UUID(),
               comment='ID CCT phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('trang_thai',
               existing_type=postgresql.ENUM('DANG_DANH_GIA', 'CHO_TONG_HOP', 'DA_TONG_HOP', 'CHO_PHE_DUYET', 'HOAN_THANH', 'CO_KIEN_NGHI', name='trang_thai_danh_gia_enum'),
               comment='Trạng thái đánh giá',
               existing_nullable=False,
               existing_server_default=sa.text("'DANG_DANH_GIA'::trang_thai_danh_gia_enum"))
        batch_op.alter_column('ngay_tong_hop',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Ngày TCCB tổng hợp',
               existing_nullable=True)
        batch_op.alter_column('ngay_de_xuat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Ngày Trưởng ĐV đề xuất',
               existing_nullable=True)
        batch_op.alter_column('ngay_phe_duyet',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Ngày CCT phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('uu_diem',
               existing_type=sa.TEXT(),
               comment='Ưu điểm nổi bật',
               existing_nullable=True)
        batch_op.alter_column('han_che',
               existing_type=sa.TEXT(),
               comment='Hạn chế, khuyết điểm',
               existing_nullable=True)
        batch_op.alter_column('ghi_chu',
               existing_type=sa.TEXT(),
               comment='Ghi chú khác',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Đánh dấu đã xóa (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_index('idx_danh_gia_don_vi_thang_nam', ['thang', 'nam'], unique=False, postgresql_include=['diem_tong', 'muc_xep_loai_chinh_thuc'])
        batch_op.create_index(batch_op.f('ix_danh_gia_thang_cong_chuc_id'), ['cong_chuc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_thang_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_thang_muc_xep_loai_chinh_thuc'), ['muc_xep_loai_chinh_thuc'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_thang_trang_thai'), ['trang_thai'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='Đánh giá tổng hợp tháng của công chức'
    )

    with op.batch_alter_table('danh_muc_sp_cong_viec', schema=None) as batch_op:
        batch_op.alter_column('ma_danh_muc',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã danh mục công việc',
               existing_nullable=False)
        batch_op.alter_column('ten_cong_viec',
               existing_type=sa.VARCHAR(length=500),
               comment='Tên công việc chi tiết',
               existing_nullable=False)
        batch_op.alter_column('mo_ta',
               existing_type=sa.TEXT(),
               comment='Mô tả chi tiết công việc',
               existing_nullable=True)
        batch_op.alter_column('sp_chuan_id',
               existing_type=sa.UUID(),
               comment='ID loại SP chuẩn (SP1-SP4)',
               existing_nullable=False)
        batch_op.alter_column('don_vi_ap_dung_id',
               existing_type=sa.UUID(),
               comment='ID đơn vị áp dụng (NULL = toàn Chi cục)',
               existing_nullable=True)
        batch_op.alter_column('nhom_cong_viec',
               existing_type=sa.VARCHAR(length=100),
               comment='Nhóm công việc (để filter)',
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment='Còn sử dụng',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Đánh dấu đã xóa (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_index(batch_op.f('ix_danh_muc_sp_cong_viec_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_muc_sp_cong_viec_nhom_cong_viec'), ['nhom_cong_viec'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='Danh mục sản phẩm/công việc cụ thể của Chi cục'
    )

    with op.batch_alter_table('don_vi', schema=None) as batch_op:
        batch_op.alter_column('ma_don_vi',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã đơn vị (unique)',
               existing_nullable=False)
        batch_op.alter_column('ten_don_vi',
               existing_type=sa.VARCHAR(length=200),
               comment='Tên đầy đủ của đơn vị',
               existing_nullable=False)
        batch_op.alter_column('ten_viet_tat',
               existing_type=sa.VARCHAR(length=50),
               comment='Tên viết tắt (VD: VP, TCCB, HQCK-HG)',
               existing_nullable=True)
        batch_op.alter_column('loai_don_vi',
               existing_type=postgresql.ENUM('LANH_DAO_CHI_CUC', 'PHONG', 'DOI', 'HAI_QUAN_CUA_KHAU', name='loai_don_vi_enum'),
               comment='Loại đơn vị: PHONG, DOI, HAI_QUAN_CUA_KHAU',
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.UUID(),
               comment='ID đơn vị cha (nếu có phân cấp)',
               existing_nullable=True)
        batch_op.alter_column('thu_tu_hien_thi',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Thứ tự hiển thị trong danh sách',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment='Đơn vị còn hoạt động',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Đánh dấu đã xóa (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_constraint('don_vi_ma_don_vi_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_don_vi_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_don_vi_ma_don_vi'), ['ma_don_vi'], unique=True)
        batch_op.drop_table_comment(
        existing_comment='Đơn vị (Phòng/Đội/HQCK) trong Chi cục'
    )

    with op.batch_alter_table('ke_khai_cong_viec', schema=None) as batch_op:
        batch_op.alter_column('cong_chuc_id',
               existing_type=sa.UUID(),
               comment='ID công chức kê khai',
               existing_nullable=False)
        batch_op.alter_column('thang',
               existing_type=sa.INTEGER(),
               comment='Tháng kê khai (1-12)',
               existing_nullable=False)
        batch_op.alter_column('nam',
               existing_type=sa.INTEGER(),
               comment='Năm kê khai',
               existing_nullable=False)
        batch_op.alter_column('ngay_thuc_hien',
               existing_type=sa.DATE(),
               comment='Ngày thực hiện công việc',
               existing_nullable=True)
        batch_op.alter_column('danh_muc_sp_id',
               existing_type=sa.UUID(),
               comment='ID công việc trong danh mục',
               existing_nullable=False)
        batch_op.alter_column('cap_do_id',
               existing_type=sa.UUID(),
               comment='ID cấp độ phức tạp',
               existing_nullable=False)
        batch_op.alter_column('so_luong',
               existing_type=sa.INTEGER(),
               comment='Số lượng (kê khai gộp)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('he_so_thuc_te',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Hệ số thực tế (chỉ dùng cho C5)',
               existing_nullable=True)
        batch_op.alter_column('nguoi_phe_duyet_id',
               existing_type=sa.UUID(),
               comment='ID người phê duyệt (CC chọn Phó ĐV)',
               existing_nullable=True)
        batch_op.alter_column('mo_ta_cong_viec',
               existing_type=sa.TEXT(),
               comment='Mô tả chi tiết công việc',
               existing_nullable=True)
        batch_op.alter_column('is_doi_moi_sang_tao',
               existing_type=sa.BOOLEAN(),
               comment='Có tính đổi mới sáng tạo không',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ngay_deadline',
               existing_type=sa.DATE(),
               comment='Hạn hoàn thành',
               existing_nullable=True)
        batch_op.alter_column('ngay_hoan_thanh',
               existing_type=sa.DATE(),
               comment='Ngày hoàn thành thực tế',
               existing_nullable=True)
        batch_op.alter_column('trang_thai',
               existing_type=postgresql.ENUM('NHAP', 'CHO_PHE_DUYET', 'DA_PHE_DUYET', 'TU_CHOI', 'HUY', name='trang_thai_ke_khai_enum'),
               comment='Trạng thái kê khai',
               existing_nullable=False,
               existing_server_default=sa.text("'NHAP'::trang_thai_ke_khai_enum"))
        batch_op.alter_column('so_sp_goc_quy_doi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Số SP gốc sau quy đổi',
               existing_nullable=True)
        batch_op.alter_column('so_sp_chat_luong',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='SP sau khi trừ lỗi chất lượng',
               existing_nullable=True)
        batch_op.alter_column('so_sp_tien_do',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='SP sau khi trừ lỗi tiến độ',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Đánh dấu đã xóa (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_index(batch_op.f('ix_ke_khai_cong_viec_cong_chuc_id'), ['cong_chuc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ke_khai_cong_viec_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_ke_khai_cong_viec_nguoi_phe_duyet_id'), ['nguoi_phe_duyet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ke_khai_cong_viec_trang_thai'), ['trang_thai'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='Bản kê khai công việc của công chức'
    )

    with op.batch_alter_table('lanh_dao_chi_so', schema=None) as batch_op:
        batch_op.alter_column('danh_gia_thang_id',
               existing_type=sa.UUID(),
               comment='ID đánh giá tháng (1-1)',
               existing_nullable=False)
        batch_op.alter_column('chi_so_d',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Chỉ số d (0.5 hoặc 1.0)',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('ghi_chu_d',
               existing_type=sa.TEXT(),
               comment='Ghi chú cho chỉ số d',
               existing_nullable=True)
        batch_op.alter_column('co_cc_khong_hoan_thanh',
               existing_type=sa.BOOLEAN(),
               comment='Có CC không hoàn thành nhiệm vụ',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('chi_so_dd',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Chỉ số đ (0.5 hoặc 1.0)',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('ghi_chu_dd',
               existing_type=sa.TEXT(),
               comment='Ghi chú cho chỉ số đ',
               existing_nullable=True)
        batch_op.alter_column('co_ton_tai_cham_tre',
               existing_type=sa.BOOLEAN(),
               comment='Có tồn tại, chậm trễ trong đơn vị',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('chi_so_e',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Chỉ số e (0.5 hoặc 1.0)',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('ghi_chu_e',
               existing_type=sa.TEXT(),
               comment='Ghi chú cho chỉ số e',
               existing_nullable=True)
        batch_op.alter_column('co_mau_thuan_noi_bo',
               existing_type=sa.BOOLEAN(),
               comment='Có mâu thuẫn nội bộ',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_table_comment(
        existing_comment='Chỉ số d, đ, e cho lãnh đạo'
    )

    with op.batch_alter_table('phe_duyet_sp', schema=None) as batch_op:
        batch_op.alter_column('ke_khai_id',
               existing_type=sa.UUID(),
               comment='ID bản kê khai',
               existing_nullable=False)
        batch_op.alter_column('nguoi_phe_duyet_id',
               existing_type=sa.UUID(),
               comment='ID người phê duyệt',
               existing_nullable=False)
        batch_op.alter_column('trang_thai',
               existing_type=postgresql.ENUM('CHO_XU_LY', 'PHE_DUYET', 'TU_CHOI', 'YEU_CAU_SUA', name='trang_thai_phe_duyet_enum'),
               comment='Kết quả phê duyệt',
               existing_nullable=False)
        batch_op.alter_column('lan_loi_chat_luong',
               existing_type=sa.INTEGER(),
               comment='Số lần lỗi chất lượng',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('lan_loi_tien_do',
               existing_type=sa.INTEGER(),
               comment='Số lần lỗi tiến độ',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ghi_chu',
               existing_type=sa.TEXT(),
               comment='Ghi chú của người phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('ly_do_tu_choi',
               existing_type=sa.TEXT(),
               comment='Lý do từ chối (nếu từ chối)',
               existing_nullable=True)
        batch_op.alter_column('ngay_phe_duyet',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời điểm phê duyệt',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_index(batch_op.f('ix_phe_duyet_sp_ke_khai_id'), ['ke_khai_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phe_duyet_sp_nguoi_phe_duyet_id'), ['nguoi_phe_duyet_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='Lịch sử phê duyệt sản phẩm'
    )

    with op.batch_alter_table('sp_cong_viec_chuan', schema=None) as batch_op:
        batch_op.alter_column('ma_sp',
               existing_type=sa.VARCHAR(length=10),
               comment='Mã sản phẩm: SP1, SP2, SP3, SP4',
               existing_nullable=False)
        batch_op.alter_column('ten_sp',
               existing_type=sa.VARCHAR(length=200),
               comment='Tên sản phẩm chuẩn',
               existing_nullable=False)
        batch_op.alter_column('mo_ta',
               existing_type=sa.TEXT(),
               comment='Mô tả chi tiết',
               existing_nullable=True)
        batch_op.alter_column('thoi_gian_phut',
               existing_type=sa.INTEGER(),
               comment='Thời gian thực hiện (phút)',
               existing_nullable=False)
        batch_op.alter_column('he_so_quy_doi_sp1',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Hệ số quy đổi về SP gốc (SP1=1, SP2/3/4=12)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::numeric"))
        batch_op.alter_column('is_sp_goc',
               existing_type=sa.BOOLEAN(),
               comment='Là SP gốc (chỉ SP1 = TRUE)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment='Còn sử dụng',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_table_comment(
        existing_comment='Sản phẩm công việc chuẩn (SP1-SP4)'
    )

    with op.batch_alter_table('tieu_chi_chung_danh_gia', schema=None) as batch_op:
        batch_op.alter_column('danh_gia_thang_id',
               existing_type=sa.UUID(),
               comment='ID đánh giá tháng',
               existing_nullable=False)
        batch_op.alter_column('nhom_tieu_chi',
               existing_type=sa.INTEGER(),
               comment='Nhóm tiêu chí (1, 2, 3)',
               existing_nullable=False)
        batch_op.alter_column('ma_tieu_chi',
               existing_type=sa.VARCHAR(length=10),
               comment='Mã tiêu chí (1.1, 1.2, 2.1, ...)',
               existing_nullable=False)
        batch_op.alter_column('ten_tieu_chi',
               existing_type=sa.VARCHAR(length=500),
               comment='Tên tiêu chí',
               existing_nullable=True)
        batch_op.alter_column('diem_toi_da',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='Điểm tối đa của tiêu chí',
               existing_nullable=False)
        batch_op.alter_column('diem_tu_cham',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='Điểm CC tự chấm',
               existing_nullable=True)
        batch_op.alter_column('diem_phe_duyet',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='Điểm lãnh đạo phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('nguoi_phe_duyet_id',
               existing_type=sa.UUID(),
               comment='ID người phê duyệt điểm',
               existing_nullable=True)
        batch_op.alter_column('ngay_phe_duyet',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Ngày phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('ghi_chu',
               existing_type=sa.TEXT(),
               comment='Ghi chú của người phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_index(batch_op.f('ix_tieu_chi_chung_danh_gia_danh_gia_thang_id'), ['danh_gia_thang_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='Chi tiết điểm tiêu chí chung (Nhóm I, II, III)'
    )

    with op.batch_alter_table('vai_tro', schema=None) as batch_op:
        batch_op.alter_column('ma_vai_tro',
               existing_type=sa.VARCHAR(length=50),
               comment='Mã vai trò (VD: CCT, PCCT, TDV)',
               existing_nullable=False)
        batch_op.alter_column('ten_vai_tro',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên hiển thị (VD: Chi cục trưởng)',
               existing_nullable=False)
        batch_op.alter_column('cap_bac',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'CHI_CUC_TRUONG', 'PHO_CHI_CUC_TRUONG', 'TRUONG_DON_VI', 'PHO_DON_VI', 'CONG_CHUC', 'TCCB', name='cap_bac_vai_tro_enum'),
               comment='Cấp bậc trong hệ thống phân quyền',
               existing_nullable=False)
        batch_op.alter_column('mo_ta',
               existing_type=sa.TEXT(),
               comment='Mô tả chi tiết vai trò',
               existing_nullable=True)
        batch_op.alter_column('is_lanh_dao',
               existing_type=sa.BOOLEAN(),
               comment='Có phải lãnh đạo không (CCT, PCCT, TDV, PDV)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('quyen_han',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Danh sách quyền chi tiết (JSON)',
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment='Vai trò còn sử dụng',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_vai_tro_ma')
        batch_op.drop_constraint('vai_tro_ma_vai_tro_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_vai_tro_ma_vai_tro'), ['ma_vai_tro'], unique=True)
        batch_op.drop_table_comment(
        existing_comment='Vai trò trong hệ thống phân quyền'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vai_tro', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Vai trò trong hệ thống phân quyền',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_vai_tro_ma_vai_tro'))
        batch_op.create_unique_constraint('vai_tro_ma_vai_tro_key', ['ma_vai_tro'])
        batch_op.create_index('idx_vai_tro_ma', ['ma_vai_tro'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Vai trò còn sử dụng',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('quyen_han',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Danh sách quyền chi tiết (JSON)',
               existing_nullable=True)
        batch_op.alter_column('is_lanh_dao',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Có phải lãnh đạo không (CCT, PCCT, TDV, PDV)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('mo_ta',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Mô tả chi tiết vai trò',
               existing_nullable=True)
        batch_op.alter_column('cap_bac',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'CHI_CUC_TRUONG', 'PHO_CHI_CUC_TRUONG', 'TRUONG_DON_VI', 'PHO_DON_VI', 'CONG_CHUC', 'TCCB', name='cap_bac_vai_tro_enum'),
               comment=None,
               existing_comment='Cấp bậc trong hệ thống phân quyền',
               existing_nullable=False)
        batch_op.alter_column('ten_vai_tro',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tên hiển thị (VD: Chi cục trưởng)',
               existing_nullable=False)
        batch_op.alter_column('ma_vai_tro',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Mã vai trò (VD: CCT, PCCT, TDV)',
               existing_nullable=False)

    with op.batch_alter_table('tieu_chi_chung_danh_gia', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Chi tiết điểm tiêu chí chung (Nhóm I, II, III)',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_tieu_chi_chung_danh_gia_danh_gia_thang_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('ghi_chu',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ghi chú của người phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('ngay_phe_duyet',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Ngày phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('nguoi_phe_duyet_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID người phê duyệt điểm',
               existing_nullable=True)
        batch_op.alter_column('diem_phe_duyet',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment=None,
               existing_comment='Điểm lãnh đạo phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('diem_tu_cham',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment=None,
               existing_comment='Điểm CC tự chấm',
               existing_nullable=True)
        batch_op.alter_column('diem_toi_da',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment=None,
               existing_comment='Điểm tối đa của tiêu chí',
               existing_nullable=False)
        batch_op.alter_column('ten_tieu_chi',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Tên tiêu chí',
               existing_nullable=True)
        batch_op.alter_column('ma_tieu_chi',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Mã tiêu chí (1.1, 1.2, 2.1, ...)',
               existing_nullable=False)
        batch_op.alter_column('nhom_tieu_chi',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Nhóm tiêu chí (1, 2, 3)',
               existing_nullable=False)
        batch_op.alter_column('danh_gia_thang_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID đánh giá tháng',
               existing_nullable=False)

    with op.batch_alter_table('sp_cong_viec_chuan', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Sản phẩm công việc chuẩn (SP1-SP4)',
        existing_comment=None
    )
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Còn sử dụng',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('is_sp_goc',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Là SP gốc (chỉ SP1 = TRUE)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('he_so_quy_doi_sp1',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Hệ số quy đổi về SP gốc (SP1=1, SP2/3/4=12)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::numeric"))
        batch_op.alter_column('thoi_gian_phut',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Thời gian thực hiện (phút)',
               existing_nullable=False)
        batch_op.alter_column('mo_ta',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Mô tả chi tiết',
               existing_nullable=True)
        batch_op.alter_column('ten_sp',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Tên sản phẩm chuẩn',
               existing_nullable=False)
        batch_op.alter_column('ma_sp',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Mã sản phẩm: SP1, SP2, SP3, SP4',
               existing_nullable=False)

    with op.batch_alter_table('phe_duyet_sp', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Lịch sử phê duyệt sản phẩm',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_phe_duyet_sp_nguoi_phe_duyet_id'))
        batch_op.drop_index(batch_op.f('ix_phe_duyet_sp_ke_khai_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('ngay_phe_duyet',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời điểm phê duyệt',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ly_do_tu_choi',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Lý do từ chối (nếu từ chối)',
               existing_nullable=True)
        batch_op.alter_column('ghi_chu',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ghi chú của người phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('lan_loi_tien_do',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Số lần lỗi tiến độ',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('lan_loi_chat_luong',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Số lần lỗi chất lượng',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('trang_thai',
               existing_type=postgresql.ENUM('CHO_XU_LY', 'PHE_DUYET', 'TU_CHOI', 'YEU_CAU_SUA', name='trang_thai_phe_duyet_enum'),
               comment=None,
               existing_comment='Kết quả phê duyệt',
               existing_nullable=False)
        batch_op.alter_column('nguoi_phe_duyet_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID người phê duyệt',
               existing_nullable=False)
        batch_op.alter_column('ke_khai_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID bản kê khai',
               existing_nullable=False)

    with op.batch_alter_table('lanh_dao_chi_so', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Chỉ số d, đ, e cho lãnh đạo',
        existing_comment=None
    )
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('co_mau_thuan_noi_bo',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Có mâu thuẫn nội bộ',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ghi_chu_e',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ghi chú cho chỉ số e',
               existing_nullable=True)
        batch_op.alter_column('chi_so_e',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Chỉ số e (0.5 hoặc 1.0)',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('co_ton_tai_cham_tre',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Có tồn tại, chậm trễ trong đơn vị',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ghi_chu_dd',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ghi chú cho chỉ số đ',
               existing_nullable=True)
        batch_op.alter_column('chi_so_dd',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Chỉ số đ (0.5 hoặc 1.0)',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('co_cc_khong_hoan_thanh',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Có CC không hoàn thành nhiệm vụ',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ghi_chu_d',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ghi chú cho chỉ số d',
               existing_nullable=True)
        batch_op.alter_column('chi_so_d',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Chỉ số d (0.5 hoặc 1.0)',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('danh_gia_thang_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID đánh giá tháng (1-1)',
               existing_nullable=False)

    with op.batch_alter_table('ke_khai_cong_viec', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Bản kê khai công việc của công chức',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_ke_khai_cong_viec_trang_thai'))
        batch_op.drop_index(batch_op.f('ix_ke_khai_cong_viec_nguoi_phe_duyet_id'))
        batch_op.drop_index(batch_op.f('ix_ke_khai_cong_viec_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_ke_khai_cong_viec_cong_chuc_id'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Đánh dấu đã xóa (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('so_sp_tien_do',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='SP sau khi trừ lỗi tiến độ',
               existing_nullable=True)
        batch_op.alter_column('so_sp_chat_luong',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='SP sau khi trừ lỗi chất lượng',
               existing_nullable=True)
        batch_op.alter_column('so_sp_goc_quy_doi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Số SP gốc sau quy đổi',
               existing_nullable=True)
        batch_op.alter_column('trang_thai',
               existing_type=postgresql.ENUM('NHAP', 'CHO_PHE_DUYET', 'DA_PHE_DUYET', 'TU_CHOI', 'HUY', name='trang_thai_ke_khai_enum'),
               comment=None,
               existing_comment='Trạng thái kê khai',
               existing_nullable=False,
               existing_server_default=sa.text("'NHAP'::trang_thai_ke_khai_enum"))
        batch_op.alter_column('ngay_hoan_thanh',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày hoàn thành thực tế',
               existing_nullable=True)
        batch_op.alter_column('ngay_deadline',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Hạn hoàn thành',
               existing_nullable=True)
        batch_op.alter_column('is_doi_moi_sang_tao',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Có tính đổi mới sáng tạo không',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('mo_ta_cong_viec',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Mô tả chi tiết công việc',
               existing_nullable=True)
        batch_op.alter_column('nguoi_phe_duyet_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID người phê duyệt (CC chọn Phó ĐV)',
               existing_nullable=True)
        batch_op.alter_column('he_so_thuc_te',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Hệ số thực tế (chỉ dùng cho C5)',
               existing_nullable=True)
        batch_op.alter_column('so_luong',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Số lượng (kê khai gộp)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('cap_do_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID cấp độ phức tạp',
               existing_nullable=False)
        batch_op.alter_column('danh_muc_sp_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID công việc trong danh mục',
               existing_nullable=False)
        batch_op.alter_column('ngay_thuc_hien',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày thực hiện công việc',
               existing_nullable=True)
        batch_op.alter_column('nam',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Năm kê khai',
               existing_nullable=False)
        batch_op.alter_column('thang',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tháng kê khai (1-12)',
               existing_nullable=False)
        batch_op.alter_column('cong_chuc_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID công chức kê khai',
               existing_nullable=False)

    with op.batch_alter_table('don_vi', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Đơn vị (Phòng/Đội/HQCK) trong Chi cục',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_don_vi_ma_don_vi'))
        batch_op.drop_index(batch_op.f('ix_don_vi_is_deleted'))
        batch_op.create_unique_constraint('don_vi_ma_don_vi_key', ['ma_don_vi'])
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Đánh dấu đã xóa (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Đơn vị còn hoạt động',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('thu_tu_hien_thi',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Thứ tự hiển thị trong danh sách',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('parent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID đơn vị cha (nếu có phân cấp)',
               existing_nullable=True)
        batch_op.alter_column('loai_don_vi',
               existing_type=postgresql.ENUM('LANH_DAO_CHI_CUC', 'PHONG', 'DOI', 'HAI_QUAN_CUA_KHAU', name='loai_don_vi_enum'),
               comment=None,
               existing_comment='Loại đơn vị: PHONG, DOI, HAI_QUAN_CUA_KHAU',
               existing_nullable=False)
        batch_op.alter_column('ten_viet_tat',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tên viết tắt (VD: VP, TCCB, HQCK-HG)',
               existing_nullable=True)
        batch_op.alter_column('ten_don_vi',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Tên đầy đủ của đơn vị',
               existing_nullable=False)
        batch_op.alter_column('ma_don_vi',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã đơn vị (unique)',
               existing_nullable=False)

    with op.batch_alter_table('danh_muc_sp_cong_viec', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Danh mục sản phẩm/công việc cụ thể của Chi cục',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_danh_muc_sp_cong_viec_nhom_cong_viec'))
        batch_op.drop_index(batch_op.f('ix_danh_muc_sp_cong_viec_is_deleted'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Đánh dấu đã xóa (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Còn sử dụng',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('nhom_cong_viec',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nhóm công việc (để filter)',
               existing_nullable=True)
        batch_op.alter_column('don_vi_ap_dung_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID đơn vị áp dụng (NULL = toàn Chi cục)',
               existing_nullable=True)
        batch_op.alter_column('sp_chuan_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID loại SP chuẩn (SP1-SP4)',
               existing_nullable=False)
        batch_op.alter_column('mo_ta',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Mô tả chi tiết công việc',
               existing_nullable=True)
        batch_op.alter_column('ten_cong_viec',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Tên công việc chi tiết',
               existing_nullable=False)
        batch_op.alter_column('ma_danh_muc',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã danh mục công việc',
               existing_nullable=False)

    with op.batch_alter_table('danh_gia_thang', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Đánh giá tổng hợp tháng của công chức',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_danh_gia_thang_trang_thai'))
        batch_op.drop_index(batch_op.f('ix_danh_gia_thang_muc_xep_loai_chinh_thuc'))
        batch_op.drop_index(batch_op.f('ix_danh_gia_thang_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_danh_gia_thang_cong_chuc_id'))
        batch_op.drop_index('idx_danh_gia_don_vi_thang_nam', postgresql_include=['diem_tong', 'muc_xep_loai_chinh_thuc'])
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Đánh dấu đã xóa (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('ghi_chu',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ghi chú khác',
               existing_nullable=True)
        batch_op.alter_column('han_che',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Hạn chế, khuyết điểm',
               existing_nullable=True)
        batch_op.alter_column('uu_diem',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ưu điểm nổi bật',
               existing_nullable=True)
        batch_op.alter_column('ngay_phe_duyet',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Ngày CCT phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('ngay_de_xuat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Ngày Trưởng ĐV đề xuất',
               existing_nullable=True)
        batch_op.alter_column('ngay_tong_hop',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Ngày TCCB tổng hợp',
               existing_nullable=True)
        batch_op.alter_column('trang_thai',
               existing_type=postgresql.ENUM('DANG_DANH_GIA', 'CHO_TONG_HOP', 'DA_TONG_HOP', 'CHO_PHE_DUYET', 'HOAN_THANH', 'CO_KIEN_NGHI', name='trang_thai_danh_gia_enum'),
               comment=None,
               existing_comment='Trạng thái đánh giá',
               existing_nullable=False,
               existing_server_default=sa.text("'DANG_DANH_GIA'::trang_thai_danh_gia_enum"))
        batch_op.alter_column('nguoi_phe_duyet_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID CCT phê duyệt',
               existing_nullable=True)
        batch_op.alter_column('nguoi_de_xuat_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID Trưởng ĐV đề xuất',
               existing_nullable=True)
        batch_op.alter_column('ly_do_dieu_chinh',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Lý do nếu khác với xếp loại tự động',
               existing_nullable=True)
        batch_op.alter_column('muc_xep_loai_chinh_thuc',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='muc_xep_loai_enum'),
               comment=None,
               existing_comment='Mức xếp loại chính thức (CCT quyết định)',
               existing_nullable=True)
        batch_op.alter_column('muc_xep_loai_de_xuat',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='muc_xep_loai_enum'),
               comment=None,
               existing_comment='Mức xếp loại Trưởng ĐV đề xuất',
               existing_nullable=True)
        batch_op.alter_column('muc_xep_loai_tu_dong',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', name='muc_xep_loai_enum'),
               comment=None,
               existing_comment='Mức xếp loại tự động (theo điểm)',
               existing_nullable=True)
        batch_op.alter_column('diem_tong',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Điểm tổng (0-100)',
               existing_nullable=True)
        batch_op.alter_column('diem_tien_do',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Điểm tiến độ (c)',
               existing_nullable=True)
        batch_op.alter_column('diem_chat_luong',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Điểm chất lượng (b)',
               existing_nullable=True)
        batch_op.alter_column('diem_so_luong',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Điểm số lượng (a)',
               existing_nullable=True)
        batch_op.alter_column('diem_kpi',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Điểm KPI (tỷ lệ 0-1)',
               existing_nullable=True)
        batch_op.alter_column('diem_tieu_chi_chung',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Tổng điểm tiêu chí chung (0-30)',
               existing_nullable=True)
        batch_op.alter_column('so_ngay_nghi_phep',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Số ngày nghỉ phép',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('so_ngay_lam_viec',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Số ngày làm việc trong tháng',
               existing_nullable=True)
        batch_op.alter_column('so_sp_goc_duoc_giao',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Số SP gốc được giao (tự động tính)',
               existing_nullable=True)
        batch_op.alter_column('nam',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Năm đánh giá',
               existing_nullable=False)
        batch_op.alter_column('thang',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tháng đánh giá (1-12)',
               existing_nullable=False)
        batch_op.alter_column('cong_chuc_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID công chức được đánh giá',
               existing_nullable=False)

    with op.batch_alter_table('cong_chuc', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Công chức Chi cục Hải quan KV8',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_cong_chuc_vai_tro_id'))
        batch_op.drop_index(batch_op.f('ix_cong_chuc_username'))
        batch_op.drop_index(batch_op.f('ix_cong_chuc_ma_cc'))
        batch_op.drop_index(batch_op.f('ix_cong_chuc_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_cong_chuc_is_active'))
        batch_op.drop_index(batch_op.f('ix_cong_chuc_don_vi_id'))
        batch_op.create_index('idx_cong_chuc_username', ['username'], unique=False)
        batch_op.create_unique_constraint('cong_chuc_username_key', ['username'])
        batch_op.create_unique_constraint('cong_chuc_ma_cc_key', ['ma_cc'])
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Đánh dấu đã xóa (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Lần đăng nhập cuối',
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Mật khẩu đã hash (bcrypt)',
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tên đăng nhập (mặc định = ma_cc)',
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Tài khoản còn hoạt động',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('is_lanh_dao',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Có phải lãnh đạo không (denormalized từ vai_tro)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ngay_vao_chi_cuc',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày về Chi cục KV VIII',
               existing_nullable=True)
        batch_op.alter_column('ngay_vao_nganh',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày vào ngành Hải quan',
               existing_nullable=True)
        batch_op.alter_column('chuc_vu',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Chức vụ hiển thị (VD: Chánh Văn phòng)',
               existing_nullable=True)
        batch_op.alter_column('vai_tro_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID vai trò trong hệ thống',
               existing_nullable=False)
        batch_op.alter_column('don_vi_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID đơn vị công tác',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Email công vụ',
               existing_nullable=True)
        batch_op.alter_column('so_dien_thoai',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Số điện thoại liên hệ',
               existing_nullable=True)
        batch_op.alter_column('gioi_tinh',
               existing_type=postgresql.ENUM('NAM', 'NU', name='gioi_tinh_enum'),
               comment=None,
               existing_comment='Giới tính: NAM, NU',
               existing_nullable=True)
        batch_op.alter_column('ngay_sinh',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày sinh',
               existing_nullable=True)
        batch_op.alter_column('ho_ten',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Họ và tên đầy đủ',
               existing_nullable=False)
        batch_op.alter_column('ma_cc',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã công chức (unique, làm username)',
               existing_nullable=False)

    with op.batch_alter_table('cap_do_phuc_tap', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Cấp độ phức tạp công việc (C1-C5)',
        existing_comment=None
    )
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian cập nhật cuối',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian tạo record',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Còn sử dụng',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('thu_tu',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Thứ tự sắp xếp (1-5)',
               existing_nullable=False)
        batch_op.alter_column('is_theo_thuc_te',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='C5 = TRUE (hệ số do lãnh đạo nhập)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('he_so_sp2',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Hệ số nhân khi áp dụng cho SP2/SP3/SP4',
               existing_nullable=False)
        batch_op.alter_column('he_so_sp1',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Hệ số nhân khi áp dụng cho SP1',
               existing_nullable=False)
        batch_op.alter_column('mo_ta',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Mô tả tiêu chí phân loại',
               existing_nullable=True)
        batch_op.alter_column('ten_cap_do',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tên cấp độ (VD: Dễ - Đơn giản)',
               existing_nullable=False)
        batch_op.alter_column('ma_cap_do',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Mã cấp độ: C1, C2, C3, C4, C5',
               existing_nullable=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Audit log - ghi lại mọi thay đổi dữ liệu',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_log_record_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary Key (UUID)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời điểm thay đổi',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='User agent của request',
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='IP address của request',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID người thực hiện (từ app.current_user_id)',
               existing_nullable=True)
        batch_op.alter_column('new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Giá trị mới (cho INSERT/UPDATE)',
               existing_nullable=True)
        batch_op.alter_column('old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Giá trị cũ (cho UPDATE/DELETE)',
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=postgresql.ENUM('INSERT', 'UPDATE', 'DELETE', name='audit_action_enum'),
               comment=None,
               existing_comment='Loại hành động: INSERT/UPDATE/DELETE',
               existing_nullable=False)
        batch_op.alter_column('record_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID của record bị thay đổi',
               existing_nullable=False)
        batch_op.alter_column('table_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tên bảng bị thay đổi',
               existing_nullable=False)

    with op.batch_alter_table('dang_ky_nghi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dang_ky_nghi_trang_thai'))
        batch_op.drop_index(batch_op.f('ix_dang_ky_nghi_nguoi_phe_duyet_id'))
        batch_op.drop_index(batch_op.f('ix_dang_ky_nghi_loai_nghi'))
        batch_op.drop_index(batch_op.f('ix_dang_ky_nghi_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_dang_ky_nghi_cong_chuc_id'))
        batch_op.drop_index('idx_dang_ky_nghi_trang_thai')
        batch_op.drop_index('idx_dang_ky_nghi_thang_nam')
        batch_op.drop_index('idx_dang_ky_nghi_phe_duyet')
        batch_op.drop_index('idx_dang_ky_nghi_ngay')
        batch_op.drop_index('idx_dang_ky_nghi_loai')
        batch_op.drop_index('idx_dang_ky_nghi_kpi', postgresql_where="trang_thai = 'DA_PHE_DUYET' AND is_deleted = FALSE")
        batch_op.drop_index('idx_dang_ky_nghi_cc')

    op.drop_table('dang_ky_nghi')
    # ### end Alembic commands ###